# example docker-compose

http:
  image: ngyuki/httpbin
  ports: ["13080:80"]
  restart: always

https:
  image: ngyuki/httpbin
  ports: ["13443:443"]
  restart: always
  environment:
    HTTPS: "on"
